<a href="https://colab.research.google.com/github/MasterLWA/Python-Basics-for-Data-Science/blob/main/Learn__NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is used for working with arrays.


In [37]:
import numpy as np

* we use np.array() to create array in NumPy
* also we can access values in the nparray by their index number

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])

print(arr)

print(type(arr))

print("index 0 =",arr[0])

print("Sum of index 2 & 3 =",arr[2] + arr[3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
<class 'numpy.ndarray'>
index 0 = 1
Sum of index 2 & 3 = 7


* Slicing arrays
* We pass slice instead of index like this: [start:end].
* We can also define the step, like this: [start:end:step].

In [39]:
print(arr[1:5]) #from index 1 to 4
print(arr[3:]) #from index 3 to end
print(arr[:5]) #for begging to 4th index excluding 5
print(arr[-3:-1])
print(arr[1::2]) #using step value to 1st index to end

[2 3 4 5]
[ 4  5  6  7  8  9 10 11 12 13]
[1 2 3 4 5]
[11 12]
[ 2  4  6  8 10 12]


# 2-D Arrays

In [40]:
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr3[1, 1:4]) #1 means tupel assigned to the 1st index as well as 1:4 means slicing like print 1st index of 1st index tupel to 4th index of 1st index tupel
print(arr3[0:2, 2]) #From both elements, return index 2
print(arr3[0:2,2:4])#From both elements, return index 2 to 4

[7 8 9]
[3 8]
[[3 4]
 [8 9]]


* Checking the Data Type of an Array

In [41]:
print("Data Type is",arr.dtype)

Data Type is int64


create new String array

In [42]:
fruits = np.array(['apple', 'banana', 'cherry']) #fruits
fruits2 = np.array(["apple", "banana", "cherry"], dtype='S') #fruits as strings


In [43]:
print("data type is", fruits.dtype)
print("data type is", fruits2.dtype)

data type is <U6
data type is |S6


* The **copy** SHOULD NOT be affected by the changes made to the original array.

In [44]:
x = arr.copy()
arr[0] = 42

print("Array",arr)
print("Copy",x)

Array [42  2  3  4  5  6  7  8  9 10 11 12 13]
Copy [ 1  2  3  4  5  6  7  8  9 10 11 12 13]


* he view SHOULD be affected by the changes made to the original array

In [45]:
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5  6  7  8  9 10 11 12 13]
[31  2  3  4  5  6  7  8  9 10 11 12 13]


* Every NumPy array has the attribute **base** that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.



In [46]:
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[31  2  3  4  5  6  7  8  9 10 11 12 13]


#Shape of an Array
The shape of an array is the number of elements in each dimension

In [47]:
print("Array :", arr.shape) #this will print that array has 13 items
print("Array 2d:", arr3.shape)

Array : (13,)
Array 2d: (2, 5)



# Reshape From 1-D to 2-D
* Convert the following 1-D array with 12 elements into a 2-D array.

In [48]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr4.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


* Convert the following 1-D array with 12 elements into a 3-D array.

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Check if the returned array is a copy or a view**

In [50]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr5.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


# Array Iterating

In [51]:
for x in arr: #Iterating 1D array
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [52]:
for x in arr3: #Literating 3D array
  print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [53]:
arr7 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr7:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Joining Array
* concatenate() function

In [54]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
